-- =====================================================================
-- Migration: FRM32 K2 Scoring Metadata
-- Purpose : Store K2 weights/comments and submission scores per K2
-- Date    : 2025-11-09
-- =====================================================================

CREATE TABLE IF NOT EXISTS frm32_k2_metrics (
    k2_code VARCHAR(10) PRIMARY KEY,
    scope_en TEXT NOT NULL,
    scope_tr TEXT NOT NULL,
    weight_percentage NUMERIC(5,2) NOT NULL,
    comment_0_en TEXT NOT NULL,
    comment_0_tr TEXT NOT NULL,
    comment_3_en TEXT NOT NULL,
    comment_3_tr TEXT NOT NULL,
    comment_6_en TEXT NOT NULL,
    comment_6_tr TEXT NOT NULL,
    comment_10_en TEXT NOT NULL,
    comment_10_tr TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS frm32_submission_scores (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    submission_id UUID NOT NULL REFERENCES frm32_submissions(id) ON DELETE CASCADE,
    k2_code VARCHAR(10) NOT NULL REFERENCES frm32_k2_metrics(k2_code) ON DELETE CASCADE,
    score INT NOT NULL CHECK (score IN (0, 3, 6, 10)),
    comment_en TEXT,
    comment_tr TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE (submission_id, k2_code)
);

CREATE INDEX IF NOT EXISTS idx_frm32_submission_scores_submission
    ON frm32_submission_scores(submission_id);

CREATE INDEX IF NOT EXISTS idx_frm32_submission_scores_k2
    ON frm32_submission_scores(k2_code);

-- Seed K2 metadata
INSERT INTO frm32_k2_metrics (
    k2_code,
    scope_en,
    scope_tr,
    weight_percentage,
    comment_0_en,
    comment_0_tr,
    comment_3_en,
    comment_3_tr,
    comment_6_en,
    comment_6_tr,
    comment_10_en,
    comment_10_tr
) VALUES
('1.1', $$Committment to HSE aspects through leadership$$, $$Liderlik yoluyla İSG-Ç unsurlarına bağlılık$$, 20.00,
 $$No evidence of HSE commitment from senior management and poor HSE culture in the organisation$$,
 $$Üst yönetim düzeyinde İş Sağlığı ve Güvenliği konularına ilişkin herhangi bir taahhüt veya bağlılık göstergesi bulunmamakta olup, kuruluş genelinde İSG kültürü zayıf seviyededir.$$,
 $$Some evidence of HSE involvement by management, lacking positive HSE culture$$,
 $$Yönetim tarafından İSG konularına sınırlı düzeyde katılım gösterildiğine dair bazı kanıtlar mevcuttur; ancak kuruluşta olumlu bir İSG kültürü gelişmemiştir.$$,
 $$Evidence of active management involvement in HSE, HSE culture acceptable$$,
 $$İş Sağlığı ve Güvenliği konularında yönetimin aktif katılımına dair kanıtlar bulunmaktadır; kuruluş genelinde İSG kültürü kabul edilebilir düzeydedir.$$,
 $$Evidence of a strong, positive HSE culture in senior management and at all levels throughout the organisation$$,
 $$Üst yönetim ve organizasyonun tüm kademelerinde güçlü ve olumlu bir İSG kültürüne dair somut kanıtlar mevcuttur.$$),

('2.1', $$HSE Policy Documents$$, $$İSG-Ç Politika Belgeleri$$, 5.00,
 $$No written HSE policy endorsed by senior management$$,
 $$Üst yönetim tarafından onaylanmış yazılı bir İş Sağlığı ve Güvenliği (İSG) politikası mevcut değildir.$$,
 $$A policy statement exists on paper but has not been well communicated to the organisation.$$,
 $$Yazılı bir İSG politikası mevcut olmakla birlikte, bu politika çalışanlara açık ve anlaşılır bir şekilde duyurulmamış, kuruluş genelinde yeterince bilinmemektedir.$$,
 $$HSE policy well defined and establishes commitment to HSE, policy distributed.$$,
 $$İSG politikası detaylı olarak hazırlanmış, üst yönetimin İSG konularına olan bağlılığını yansıtmaktadır; politika tüm birimlere iletilmiştir.$$,
 $$HSE policy well defined and establishes commitment to HSE, well communicated to all employees, policy visible in the workplace$$,
 $$İSG politikası açık ve net şekilde tanımlanmış olup, İSG’ye olan bağlılığı ortaya koymaktadır; tüm çalışanlara etkin biçimde iletilmiş ve iş yerinde görünür şekilde sergilenmektedir.$$),

('2.2', $$HSE contract strategic objectives$$, $$İSG-Ç sözleşmesinin stratejik hedefleri$$, 5.00,
 $$No written strategic HSE objectives endorsed by senior management$$,
 $$Üst yönetim tarafından onaylanmış yazılı İSG stratejik hedefleri bulunmamaktadır.$$,
 $$Strategic objectives exist on paper but have not been well communicated to the organisation.$$,
 $$Stratejik hedefler kâğıt üzerinde mevcuttur ancak kuruluş geneline etkin bir şekilde iletilmemiştir.$$,
 $$HSE strategic objectives defined and distributed.$$,
 $$İSG stratejik hedefleri tanımlanmış ve organizasyon genelinde dağıtılmıştır.$$,
 $$HSE strategic objectives well defined and establishes commitment to HSE, well communicated to all employees.$$,
 $$İSG stratejik hedefleri açık ve net şekilde tanımlanmış olup, İSG’ye bağlılığı ortaya koymaktadır; tüm çalışanlara etkin bir şekilde iletilmiştir.$$),

('3.1', $$Organisational structure for HSE management$$, $$İSG-Ç Yönetimi Organizasyon Yapısı$$, 2.50,
 $$No evidence of specialist HSE resources or effective HSE communication.$$,
 $$Uzman İSG kaynaklarına veya etkin bir İSG iletişimine dair herhangi bir kanıt bulunmamaktadır.$$,
 $$Limited specialist HSE resources. Periodic HSE meetings for special operations only.$$,
 $$Uzman İSG kaynakları sınırlıdır. İSG toplantıları yalnızca özel operasyonlar için dönemsel olarak gerçekleştirilmektedir.$$,
 $$Adequate level of specialist HSE resources. HSE meetings performed regularly involving all personnel.$$,
 $$Yeterli düzeyde uzman İSG kaynakları mevcuttur. Tüm personelin katılımıyla düzenli olarak İSG toplantıları yapılmaktadır.$$,
 $$Good level of specialist HSE resources, HSE communication integrated fully into all operations.$$,
 $$İSG alanında güçlü ve yeterli uzman kaynaklar bulunmaktadır; İSG iletişimi tüm operasyonlara entegre edilmiştir.$$),

('3.2', $$HSE training of managers, supervisors and HSE critical positions$$, $$Yöneticilerin, Denetçilerin ve İSG-Ç'nin Kritik Pozisyonlarının İSG-Ç Eğitimi$$, 2.50,
 $$No specialised HSE training for managers/supervisors or senior site staff.$$,
 $$Yöneticiler, denetçiler veya kıdemli saha personeline yönelik herhangi bir uzmanlaşmış İSG eğitimi bulunmamaktadır.$$,
 $$Some specialised HSE training for managers/supervisors or senior site staff$$,
 $$Yöneticiler, denetçiler veya kıdemli saha personeline sınırlı kapsamda uzmanlaşmış İSG eğitimi sağlanmıştır.$$,
 $$HSE training provided to management but not comprehensive in content$$,
 $$Yönetim kadrosuna İSG eğitimi verilmiştir; ancak eğitim içeriği kapsamlı değildir ve tüm sorumluluk alanlarını tam olarak kapsamamaktadır.$$,
 $$Comprehensive HSE training given formally to all relevant staff on their respective responsibilities$$,
 $$Tüm ilgili personele, görev ve sorumluluklarını kapsayacak şekilde kapsamlı ve resmi bir İSG eğitimi programı uygulanmıştır.$$),

('3.3', $$General HSE training$$, $$Genel İSG-Ç Eğitimi$$, 2.50,
 $$No formal HSE training programme.$$,
 $$Kuruluşa ait resmî bir İSG eğitim programı bulunmamaktadır.$$,
 $$Verbal instructions on company procedures only. Documents provided for new employees but no on-the-job orientation by supervisor.$$,
 $$Çalışanlara yalnızca şirket prosedürlerine ilişkin sözlü talimatlar verilmektedir. Yeni çalışanlara dokümanlar sağlanmakta, ancak iş başı oryantasyonu yönetici tarafından gerçekleştirilmemektedir.$$,
 $$General HSE training provided for required tasks. Company documents provided. Supervisor outlines, explains and demonstrates employee’s job and emergency procedures.$$,
 $$Gerekli görevler için genel İSG eğitimi sağlanmaktadır. Şirket dokümanları çalışanlara verilmektedir. Yönetici, çalışanın görevini ve acil durum prosedürlerini açıklamakta, anlatmakta ve uygulamalı olarak göstermektedir.$$,
 $$Column C together with follow-up observation of employee’s performance. Additional HSE training provided to address any gaps identified and changes in job responsibilities/function.$$,
 $$C seviyesindeki uygulamalara ek olarak, çalışan performansı gözlemlenmekte ve tespit edilen eksiklikler ile görev veya fonksiyon değişikliklerine yönelik ilave İSG eğitimi sağlanmaktadır.$$),

('3.4', $$Cometence assurance$$, $$Yetkinlik Değerlendirme Sistemi$$, 2.50,
 $$No evidence of competence systems in place.$$,
 $$Yetkinlik sistemlerine dair herhangi bir kanıt bulunmamaktadır.$$,
 $$Some general competence profiles available.$$,
 $$Bazı genel yetkinlik profilleri mevcuttur.$$,
 $$Individual HSE competence profiles in place but no systematic follow-up.$$,
 $$Bireysel İSG yetkinlik profilleri oluşturulmuş ancak sistematik bir takip yapılmamaktadır.$$,
 $$Formal HSE competence system in place and ensuring that HSE competence assessment of staff is up to date.$$,
 $$Resmî bir İSG yetkinlik sistemi mevcut olup, çalışanların İSG yetkinlik değerlendirmeleri güncel olarak yapılmaktadır.$$),

('3.5', $$Contractor management process$$, $$Yüklenici Yönetim Sistemi$$, 2.50,
 $$No written process for managing contractors$$,
 $$Yüklenicilerin yönetimi için yazılı bir süreç bulunmamaktadır.$$,
 $$Basic system in place for management of contractors, selection process limited in HSE criteria.$$,
 $$Yüklenicilerin yönetimi için temel bir sistem mevcut olup, seçim süreci İSG-Ç kriterleri açısından sınırlıdır.$$,
 $$Contractors are selected with appropriate consideration of HSE abilities. Client required standards of HSE performance are communicated to their contractors.$$,
 $$Yükleniciler, İSG-Ç yeterlilikleri uygun şekilde dikkate alınarak seçilmektedir. Müşteri tarafından belirlenen İSG-Ç performans standartları yüklenicilere iletilmektedir.$$,
 $$Column C together with follow-up conducted on the HSE performance of their contractor. Contractor and their contractors work together for achievement of HSE objectives.$$,
 $$C seviyesindeki uygulamalara ek olarak, yüklenicilerin İSG-Ç performansları izlenmekte ve takip edilmektedir. Yüklenici ve alt yüklenicileri, İSG-Ç hedeflerine ulaşmak için birlikte çalışmaktadır.$$),

('3.6', $$HSE standards$$, $$İSG-Ç Standartları$$, 2.50,
 $$No HSE performance standards available.$$,
 $$İSG-Ç performans standartları mevcut değildir.$$,
 $$Basic HSE performance standards exist.$$,
 $$Temel İSG-Ç performans standartları mevcuttur.$$,
 $$Company has written HSE performance standards to cover all hazardous operations and basic requirements.$$,
 $$Şirket, tüm tehlikeli operasyonları ve temel gereksinimleri kapsayan yazılı İSG-Ç performans standartlarına sahiptir.$$,
 $$Column C together with a system of updating standards as required.$$,
 $$C seviyesindeki uygulamalara ek olarak, standartların gerektiği şekilde güncellenmesini sağlayan bir sistem bulunmaktadır.$$),

('4.1', $$Risk Assessment & Control$$, $$Risk Değerlendirmesi ve Kontrolü$$, 2.14,
 $$Company HSE-MS does not include a risk assessment process.$$,
 $$Şirketin İSG-Ç Yönetim Sistemi (İSG-Ç-MS), risk değerlendirmesi sürecini kapsamamaktadır.$$,
 $$Company HSE-MS makes reference to the need to conduct risk assessment but has no techniques to carry this out.$$,
 $$Şirketin İSG-Ç Yönetim Sistemi (İSG-Ç-MS), risk değerlendirmesi yapılması gerektiğine dair bir referans içermemektedir.$$,
 $$Company HSE-MS includes techniques for the assessment of task based and specific HSE subject risk assessments.$$,
 $$Şirketin İSG-Ç Yönetim Sistemi (İSG-Ç-MS), görev bazlı ve belirli İSG-Ç konuları için risk değerlendirmesi tekniklerini içermektedir.$$,
 $$Company HSE-MS has a comprehensive set of techniques for risk assessment of all HSE hazards with follow up on effectiveness of implemented control measures.$$,
 $$Şirketin İSG-Ç Yönetim Sistemi (İSG-Ç-MS), tüm İSG-Ç tehlikeleri için risk değerlendirmesi tekniklerini kapsamlı şekilde içermekte ve uygulanan kontrol önlemlerinin etkinliğini takip etmektedir.$$),

('4.2', $$Health Hazards$$, $$Sağlık Tehlikeleri$$, 2.14,
 $$No specific health policy and hazard management programme in place$$,
 $$Belirli bir sağlık politikası ve tehlike yönetimi programı mevcut değildir.$$,
 $$Health management programmes are in place for significant health risks e.g. malaria, substance abuse, blood borne pathogens$$,
 $$Sıtma, madde bağımlılığı, kan yoluyla bulaşan patojenler gibi önemli sağlık risklerine yönelik sağlık yönetim programları mevcuttur.$$,
 $$Comprehensive health policy and programmes cover health risks to personnel associated with the company’s activities.$$,
 $$Kapsamlı bir sağlık politikası ve programları, şirketin faaliyetleriyle ilişkili personel sağlık risklerini kapsamaktadır.$$,
 $$Column C together with regular exposure monitoring to all foreseeable health hazards and applied to all operations$$,
 $$C seviyesindeki uygulamalara ek olarak, tüm öngörülebilir sağlık tehlikelerine yönelik düzenli maruziyet izleme yapılmakta ve tüm operasyonlara uygulanmaktadır.$$),

('4.3', $$Safety hazards$$, $$Güvenlik Tehlikeleri$$, 2.14,
 $$No specific safety hazard management programmes in place.$$,
 $$Belirli bir güvenlik tehlikesi yönetimi programı mevcut değildir.$$,
 $$HSE programmes are in place for significant safety risks e.g. explosive atmospheres.$$,
 $$Patlayıcı ortamlar gibi önemli güvenlik risklerine karşı İSG-Ç programları mevcuttur.$$,
 $$Comprehensive HSE programmes cover HSE risks to personnel associated with the company’s activities.$$,
 $$Kapsamlı İSG-Ç programları, şirketin faaliyetleriyle ilişkili personel güvenlik risklerini kapsamlı bir şekilde ele almaktadır.$$,
 $$Column C together with regular monitoring of all foreseeable hazards and applied to all operations.$$,
 $$C seviyesindeki uygulamalara ek olarak, tüm öngörülebilir güvenlik tehlikelerin düzenli izlenmesi yapılmakta ve tüm operasyonlara uygulanmaktadır.$$),

('4.4', $$Logistics hazards$$, $$Lojistik Tehlikeleri$$, 2.14,
 $$No specific logistics hazard management programmes in place.$$,
 $$Belirli bir lojistik tehlike yönetimi programı mevcut değildir.$$,
 $$Logistics programmes are in place for significant logistics risks e.g. driving, poor road conditions, air transport, and marine transport.$$,
 $$Yol güvenliği, kötü yol koşulları, hava taşımacılığı ve deniz taşımacılığı gibi önemli lojistik risklere yönelik lojistik programları mevcuttur.$$,
 $$Comprehensive logistics programmes cover logistics risks to personnel and materials associated with the company’s activities.$$,
 $$Kapsamlı lojistik programları, şirketin faaliyetleriyle ilişkili olarak personel ve malzemelerin karşılaşabileceği lojistik risklerini kapsamaktadır.$$,
 $$Column C together with regular monitoring of all foreseeable hazards and applied to all operations$$,
 $$C seviyesindeki uygulamalara ek olarak, tüm öngörülebilir lojistik tehlikelerin düzenli olarak izlenmesi sağlanmakta ve bu izleme tüm operasyonlara uygulanmaktadır.$$),

('4.5', $$Environmental hazards$$, $$Çevresel Tehlikeler$$, 2.14,
 $$No specific environmental hazard management programmes in place.$$,
 $$Belirli bir çevresel tehlike yönetim programı mevcut değildir.$$,
 $$Environmental programmes are in place for significant HSE risks e.g. spills, air emissions, pollution prevention, and waste management$$,
 $$Dökülmeler, hava emisyonları, kirliliği önleme ve atık yönetimi gibi belirli İSG-Ç riskleri için çevresel programlar mevcuttur.$$,
 $$Comprehensive environmental programmes cover environmental risks associated with the company’s activities.$$,
 $$Kapsamlı çevresel programlar, şirketin faaliyetleriyle ilişkili çevresel riskleri kapsamaktadır.$$,
 $$Column C together with regular monitoring of all foreseeable hazards and applied to all operations$$,
 $$C seviyesindeki uygulamalara ek olarak, tüm öngörülebilir çevresel tehlikelerin düzenli olarak izlenmesi sağlanmakta ve bu izleme tüm operasyonlara uygulanmaktadır.$$),

('4.6', $$Security hazards$$, $$Güvenlik Tehlikeleri$$, 2.14,
 $$No specific security hazard management programmes in place.$$,
 $$Belirli bir güvenlik tehlike yönetimi programı mevcut değildir.$$,
 $$Security programmes are in place for significant security risks e.g. hostage taking, terrorist threats, location evacuation.$$,
 $$Rehine alma, terör tehditleri, bölgeden tahliye gibi belirli güvenlik riskleri için güvenlik programları mevcuttur.$$,
 $$Comprehensive security programmes cover security risks to personnel associated with the company’s activities.$$,
 $$Kapsamlı güvenlik programları, şirket faaliyetlerinden kaynaklanan personel güvenliği risklerini kapsamaktadır.$$,
 $$Column C together with regular monitoring of all foreseeable security hazards and applied to all operations$$,
 $$C seviyesindeki uygulamalara ek olarak, tüm öngörülebilir güvenlik tehlikelerin düzenli olarak izlenmesi sağlanmakta ve bu izleme tüm operasyonlara uygulanmaktadır.$$),

('4.7', $$Social responsibility hazards$$, $$Sosyal Sorumluluk Tehlikeleri$$, 2.14,
 $$No specific Social Responsibility hazard management programme in place$$,
 $$Belirli bir Sosyal Sorumluluk tehlike yönetimi programı mevcut değildir$$,
 $$Social Responsibility programmes are in place for significant Social Responsibility Risks, e.g. Community disturbances, strikes, community illnesses$$,
 $$Topluluk rahatsızlıkları, grevler ve toplum sağlığını etkileyebilecek hastalıklar gibi önemli sosyal sorumluluk risklerine yönelik sosyal sorumluluk programları yürürlüktedir.$$,
 $$Comprehensive Social Responsibility programmes cover Social Responsibility Risks associated with the company’s activities.$$,
 $$Kapsamlı sosyal sorumluluk programları, şirketin faaliyetleriyle ilişkili sosyal sorumluluk risklerini kapsamaktadır.$$,
 $$Column C together with regular monitoring of all foreseeable Social Responsibility hazards and applied to all operations$$,
 $$C seviyesindeki uygulamalara ek olarak, tüm öngörülebilir sosyal sorumluluk tehlikelerin düzenli olarak izlenmesi sağlanmakta ve bu izleme tüm operasyonlara uygulanmaktadır.$$),

('5.1', $$HSE operations manual$$, $$İSG-Ç Operasyonları Kılavuzu$$, 2.50,
 $$No HSE procedures or operations manual with integrated HSE requirements available.$$,
 $$Entegre İSG-Ç gerekliliklerini içeren herhangi bir İSG-Ç prosedürü veya operasyon el kitabı mevcut değildir.$$,
 $$Basic HSE procedures exist, scope of activities not adequately covered by the documentation available.$$,
 $$Temel İSG-Ç prosedürleri mevcuttur, ancak mevcut dokümantasyon faaliyetlerin kapsamını yeterince karşılamamaktadır.$$,
 $$Contractor has written HSE procedures to cover all hazardous operations.$$,
 $$Yüklenici, tüm tehlikeli operasyonları kapsayacak şekilde yazılı İSG-Ç prosedürlerine sahiptir.$$,
 $$Column C together with methods in place for follow-up on effectiveness of implementation and feedback for improvement.$$,
 $$C seviyesindeki uygulamalara ek olarak, etkinlik takibi ve iyileştirme için geri bildirim yöntemleri de mevcuttur.$$),

('5.2', $$Infrastructure and equipment integrity$$, $$Altyapı ve Ekipman Bütünlüğü$$, 2.50,
 $$No defined programme to identify or evaluate infrastructure and equipment condition.$$,
 $$Altyapı ve ekipman durumunu belirlemek veya değerlendirmek için tanımlanmış bir program mevcut değildir.$$,
 $$Focus is mainly on infrastructure and equipment supplied to client, as required, not comprehensive.$$,
 $$Odak noktası, yalnızca ihtiyaç duyulduğunda müşteriye sağlanan altyapı ve ekipman olup, kapsamlı bir yaklaşım bulunmamaktadır.$$,
 $$A written programme outlining requirements, responsibilities, frequency and follow-up is in effect.$$,
 $$Gereklilikleri, sorumlulukları, sıklığı ve takibi belirten yazılı bir program mevcuttur.$$,
 $$Column C together with periodic inspections conducted by management or specialists$$,
 $$C seviyesindeki uygulamalara ek olarak, yönetim veya alanında uzman kişiler tarafından yapılan periyodik denetimler de uygulanmaktadır.$$),

('5.3', $$Management of change$$, $$Değişim Yönetimi$$, 2.50,
 $$No special attention paid to managing change.$$,
 $$Değişikliklerin yönetimine özel bir önem verilmemektedir.$$,
 $$Managing change focused only on client related activities.$$,
 $$Değişikliklerin yönetimi, yalnızca müşteriyle ilişkili faaliyetlerle sınırlı tutulmuştur.$$,
 $$Company has implemented general management of change process covering all its activities.$$,
 $$Şirket, tüm faaliyetlerini kapsayan genel bir değişiklik yönetimi süreci uygulamaktadır.$$,
 $$Company has a comprehensive process and set of plans and procedures covering all activities, including follow up of effectiveness.$$,
 $$Şirketin, tüm faaliyetleri kapsayan ve etkinliğin takibini de içeren kapsamlı bir süreci ile plan ve prosedür seti mevcuttur.$$),

('5.4', $$Emergency planning and response$$, $$Acil Durum Planlaması ve Müdahalesi$$, 2.50,
 $$No special attention paid to planning for emergency response.$$,
 $$Acil durumlara müdahale planlaması konusunda özel bir önem verilmemektedir.$$,
 $$Basic emergencies covered by plans, e.g. fire, medical, spill, evacuation.$$,
 $$Temel acil durumlar, örneğin yangın, tıbbi müdahale, dökülme ve tahliye gibi durumlar planlarla kapsanmaktadır.$$,
 $$Company has a comprehensive emergency planning process covering all reasonably foreseeable emergency situations, including tests conducted.$$,
 $$Şirketin, yapılan testler de dahil olmak üzere makul ölçüde öngörülebilir tüm acil durumları kapsayan kapsamlı bir acil durum planlama süreci vardır.$$,
 $$Column C together with regularly updated plans covering all emergency situations, including follow up and improvement of effectiveness.$$,
 $$C seviyesindeki uygulamalara ek olarak, tüm acil durumları kapsayan, takibi ve etkinliğin artırılmasını da içeren düzenli olarak güncellenen planlar yer almaktadır.$$),

('6.1', $$HSE-MS implementation and active performance monitoring of work activities$$, $$İSG-Ç-MS Uygulaması ve İş Faaliyetlerinin Aktif Performans Takibi$$, 3.00,
 $$No system for formally monitoring HSE performance.$$,
 $$İSG-Ç performansını resmi olarak izlemek için bir sistem mevcut değildir.$$,
 $$Performance monitoring limited to incident statistics, i.e. Reactive only.$$,
 $$Performans izleme, yalnızca kaza istatistiklerine dayanmakta olup, bu durum yalnızca reaktif bir yaklaşımı yansıtmaktadır.$$,
 $$Company has a system for monitoring HSE performance in all specified subjects, including some pro-active performance monitoring.$$,
 $$Şirketin, tüm belirli konularda İSG-Ç performansını izlemek için bir sistemi mevcuttur, bu sistem bazı proaktif performans izlemeyi de içermektedir.$$,
 $$Column C together with monitoring of performance in all specified subjects with formal review, follow up and communication for continuous improvement.$$,
 $$C sütunu, tüm belirli konularda performans izlemeyi, resmi incelemeyi, takip etmeyi ve sürekli iyileştirme için iletişim süreçlerini içermektedir.$$),

('6.2', $$Safety performance indicators$$, $$Güvenlik Performans Göstergeleri$$, 3.00,
 $$Company supplied insufficient information to establish trends.$$,
 $$Şirket, trendleri belirlemek için yeterli bilgi sağlamadı.$$,
 $$Data set is not complete. Trends show performance is not improving.$$,
 $$Veri seti tamamlanmamıştır. Trendler, performansın iyileşmediğini göstermektedir.$$,
 $$Full information available, trends shows only minor improvement.$$,
 $$Tam bilgi mevcuttur, ancak trendler yalnızca küçük bir iyileşme göstermektedir.$$,
 $$Column C together with incident trends steadily improving and evidence of mature reporting culture.$$,
 $$C sütunu, kaza trendlerinin sürekli olarak iyileştiği ve gelişmiş bir raporlama kültürünün kanıtlarının bulunduğu bir durumu yansıtmaktadır.$$),

('6.3', $$HSE performance monitoring$$, $$İSG-Ç Performans İzleme$$, 3.00,
 $$Company supplied insufficient information.$$,
 $$Şirket yetersiz bilgi sağladı.$$,
 $$Limited performance monitoring is carried out.$$,
 $$Sınırlı performans izleme yapılmaktadır.$$,
 $$A system is in place for monitoring HSE and security performance and is recording limited data.$$,
 $$İSG-Ç ve güvenlik performansını izlemek için bir sistem mevcuttur ve sınırlı veri kaydedilmektedir.$$,
 $$Company has comprehensive monitoring processes for all HSE and security elements, performance is reviewed regularly by senior management.$$,
 $$Şirketin, tüm İSG-Ç ve güvenlik unsurları için kapsamlı izleme süreçleri mevcuttur ve performans, üst yönetim tarafından düzenli olarak gözden geçirilmektedir.$$),

('6.4', $$HSE incident and investigation follow-up$$, $$İSG-Ç Olay ve Soruşturma Takibi$$, 3.00,
 $$No system for formally investigating HSE incidents.$$,
 $$İSG-Ç kazalarını resmi olarak araştırmak için bir sistem mevcut değildir.$$,
 $$System in place for investigation of some HSE incidents, limited management participation.$$,
 $$Bazı İSG-Ç kazalarının araştırılması için bir sistem mevcuttur, ancak yönetimin katılımı sınırlıdır.$$,
 $$Investigation methods and teams are selected based on the severity or potential severity of incidents. Limited near miss investigation.$$,
 $$Araştırma yöntemleri ve ekipleri, kazaların şiddeti veya potansiyel şiddeti temel alınarak seçilmektedir. Yakın tehlike araştırması sınırlıdır.$$,
 $$Column C together with follow up of remedial actions and communication of incident learning for effective prevention. Near miss incidents investigated in the same manner as other incidents.$$,
 $$C sütunu, düzeltici eylemlerin takibi ve olay öğrenimlerinin etkili önleme için iletişimi ile birlikte mevcuttur. Yakın tehlike olayları, diğer olaylarla aynı şekilde araştırılmaktadır.$$),

('6.5', $$Statutory notifiable incidents or non compliance notices$$, $$Yasal Olarak Bildirilmesi Gereken Olaylar veya Uygunsuzluk Bildirimleri$$, 3.00,
 $$More than one occurrence of major incident in last five years$$,
 $$Son beş yılda birden fazla büyük olay meydana gelmiştir.$$,
 $$One occurrence of a major incident in the last five years$$,
 $$Son beş yılda bir büyük olay meydana gelmiştir.$$,
 $$Occurrences relate to minor incident(s) only$$,
 $$Olaylar yalnızca küçük olaylar ile ilgilidir.$$,
 $$No occurrences in the last five years$$,
 $$Son beş yılda herhangi bir olay meydana gelmemiştir.$$),

('7.1', $$Audits$$, $$Denetimler$$, 5.00,
 $$Audit process is very basic and not specific to HSE.$$,
 $$Denetim süreci çok temel olup, İSG-Ç'ye özgü değildir.$$,
 $$Basic HSE audit process, not comprehensive or structured approach.$$,
 $$Temel İSG-Ç denetim süreci, kapsamlı veya yapılandırılmış bir yaklaşıma sahip değildir.$$,
 $$HSE audit process includes details of how auditing is implemented with frequencies for key areas and requirement for auditor competence.$$,
 $$İSG-Ç denetim süreci, denetimlerin nasıl uygulanacağına dair detaylar, anahtar alanlar için denetim sıklıkları ve denetçi yeterliliği gereksinimlerini içermektedir.$$,
 $$Column C together with additional specification of management role in the audit process and follow-up on action items.$$,
 $$C sütunu, denetim sürecindeki yönetim rolüne ek olarak, eylem maddelerinin takibini de içermektedir.$$),

('7.2', $$Management review and follow-up$$, $$Yönetim Gözden Geçirilmesi ve Takibi$$, 5.00,
 $$Management review process is very basic and does not specifically include HSE aspects.$$,
 $$Yönetim gözden geçirme süreci çok temel olup, özellikle İSG-Ç yönlerini içermemektedir.$$,
 $$Management review does include a review of key HSE issues.$$,
 $$Yönetim gözden geçirmesi, anahtar İSG-Ç konularının gözden geçirilmesini içermektedir.$$,
 $$Formal reviews of the HSE Management System are regularly conducted by management for the purpose of improvement, key personnel are involved.$$,
 $$İSG-Ç Yönetim Sistemi'nin resmi gözden geçirmeleri, iyileştirme amacıyla yönetim tarafından düzenli olarak yapılmakta ve kilit personel bu süreçte yer almaktadır.$$,
 $$Column C together with a process in place to follow-up on action items to ensure effective completion.$$,
 $$C sütunu, eylem maddelerinin etkili bir şekilde tamamlanmasını sağlamak için takip sürecine sahip bir sistemle birlikte mevcuttur.$$),

('8.1', $$Certification of your HSE-MS$$, $$İSG-Ç-MS'nizin (İSG-Ç İş Yapım Yöntemi) Sertifikasyonu$$, 1.67,
 $$No certification.$$,
 $$Sertifika mevcut değildir.$$,
 $$Working towards compliance with recognised international standards, e.g. ISO 9001, ISO 14001, OHSAS 18001.$$,
 $$Tanınmış uluslararası standartlara uyum sağlamak için çalışılmaktadır, örneğin ISO 9001, ISO 14001, OHSAS 18001.$$,
 $$Working in compliance with international standards but not certified. Or system verified by a third party.$$,
 $$Uluslararası standartlarla uyum içinde çalışılmakta ancak sertifikalandırılmamış veya sistem üçüncü taraf tarafından doğrulanmamıştır.$$,
 $$Externally certified to one or more recognised international standards e.g. ISO 9001, ISO 14001, OHSAS 18001.$$,
 $$Bir veya daha fazla tanınmış uluslararası standarda, örneğin ISO 9001, ISO 14001, OHSAS 18001, dışarıdan sertifikalandırılmıştır.$$),

('8.2', $$Membership of associations$$, $$Dernek Üyelikleri$$, 1.67,
 $$No involvement with HSE through industry or trade associations.$$,
 $$Sektörel veya ticari dernekler aracılığıyla İSG-Ç ile herhangi bir ilgisi yoktur.$$,
 $$Company has membership of industry bodies/association little involvement with HSE initiatives.$$,
 $$Şirketin sektör kuruluşlarına/derneklerine üyeliği vardır ancak İSG-Ç girişimlerine sınırlı düzeyde katılım göstermektedir.$$,
 $$Company is an active member of industry bodies/associations related to HSE.$$,
 $$Şirket, İSG-Ç ile ilgili sektör kuruluşları/derneklerinin aktif bir üyesidir.$$,
 $$Column C together with industry or Client recognition/awards for HSE initiatives and/or performance.$$,
 $$C Sütunu, sektör veya müşteri tarafından İSG-Ç girişimleri ve/veya performansı için verilen takdir/ödüllerle birlikte değerlendirilir.$$),

('8.3', $$Additional features of your HSE-MS$$, $$İSG-Ç-MS'nizin (İSG-Ç Yönetim Sistemi) Ek Özellikleri$$, 1.67,
 $$No additional features to HSE MS.$$,
 $$İSG-Ç Yönetim Sistemine yönelik herhangi bir ek özellik bulunmamaktadır.$$,
 $$Some additional HSE MS features with value.$$,
 $$Değer katan bazı ek İSG-Ç Yönetim Sistemi özellikleri mevcuttur.$$,
 $$Several HSE MS features which add value.$$,
 $$Değer katan birçok İSG-Ç Yönetim Sistemi özelliği mevcuttur.$$,
 $$Column C together with industry or Client recognition/awards for HSE initiatives and/or performance.$$,
 $$C Sütunu, İSG-Ç girişimleri ve/veya performansı için sektör veya müşteri tarafından verilen takdir/ödüllerle birlikte değerlendirilir.$$);

-- Ensure weight percentages sum to 100%
DO $$
DECLARE
    total_weight NUMERIC(6,2);
BEGIN
    SELECT SUM(weight_percentage) INTO total_weight FROM frm32_k2_metrics;
    IF abs(total_weight - 100) > 0.01 THEN
        RAISE EXCEPTION 'FRM32 K2 weights must sum to 100 (current: %)', total_weight;
    END IF;
END;
$$;
