
-- =====================================================================
-- Migration: FRM33/34/35 Supervisor Question Bank
-- Purpose: Create frm_supervisor_questions table and seed questions parsed
--          from the static HTML forms (frm33.html, frm34.html, frm35.html)
-- Date: 2025-11-18
-- =====================================================================

CREATE TABLE IF NOT EXISTS frm_supervisor_questions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    form_id TEXT NOT NULL CHECK (form_id IN ('frm33', 'frm34', 'frm35')),
    question_code TEXT NOT NULL,
    question_text_en TEXT NOT NULL,
    question_text_tr TEXT,
    question_type TEXT NOT NULL DEFAULT 'text',
    is_required BOOLEAN NOT NULL DEFAULT TRUE,
    position INT NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_supervisor_questions_form_code
    ON frm_supervisor_questions(form_id, question_code);


-- Seed questions for FRM33
INSERT INTO frm_supervisor_questions (form_id, question_code, question_text_en, question_text_tr, question_type, is_required, position) VALUES
    ('frm33', '1.1', 'IOGP Assessment / Gap-Closure-Plan progress', 'IOGP Değerlendirmesi / Boşluk-Kapatma-Plan ilerlemesi', 'text', TRUE, 1),
    ('frm33', '1.2', 'Contract HSE Plan (Applicable to High Risk Contracts - Contract HSE Plans should describe how the Contractor works underneath, and interfaces with the SOCAR HSE Management System)', 'Sözleşme İSGÇ Planı (Yüksek Riskli Sözleşmeler için geçerli - Sözleşme İSGÇ Planları, Yüklenicinin SOCAR İSGÇ Yönetim Sistemi altında nasıl çalıştığını ve onunla nasıl arayüz oluşturduğunu açıklamalıdır)', 'text', TRUE, 2),
    ('frm33', '1.3', 'Project Risk Assessment - Scope Specific', 'Proje Risk Değerlendirmesi - Kapsam Özel', 'text', TRUE, 3),
    ('frm33', '1.4', 'Subcontractor Management procedure/process (also including the environment)', 'Alt yüklenici Yönetim prosedürü/süreci (çevreyi de içerir)', 'text', TRUE, 4),
    ('frm33', '1.5', 'Monthly HSE Report template shared', 'Aylık İSGÇ Rapor şablonu paylaşıldı', 'text', TRUE, 5),
    ('frm33', '1.6', 'Incident Reporting Template shared', 'Olay Raporlama Şablonu paylaşıldı', 'text', TRUE, 6),
    ('frm33', '1.7', 'Copy of Identification & Suggestion Template', 'Tanımlama ve Öneri Şablonu Kopyası', 'text', TRUE, 7),
    ('frm33', '1.8', 'Kick-off meeting completed', 'Başlangıç toplantısı tamamlandı', 'text', TRUE, 8),
    ('frm33', '2.1', 'Driver and Vehicle List (Applicable if Contractor has their own vehicles and drivers)', 'Sürücü ve Araç Listesi (Yüklenicinin kendi araçları ve sürücüleri varsa geçerlidir)', 'text', TRUE, 9),
    ('frm33', '2.2', 'Maintenance Records and Schedule (Applicable if Contractor has their own vehicles and drivers)', 'Bakım Kayıtları ve Programı (Yüklenicinin kendi araçları ve sürücüleri varsa geçerlidir)', 'text', TRUE, 10),
    ('frm33', '3.1', 'Emergency Response Plan', 'Acil Durum Müdahale Planı', 'text', TRUE, 11),
    ('frm33', '3.2', 'Details of Occupational Physician / Medical Staff / First Aiders', 'Meslek Hekimi / Tıbbi Personel / İlk Yardımcılar Detayları', 'text', TRUE, 12),
    ('frm33', '3.3', 'Fitness to Work Certificates', 'İşe Uygunluk Sertifikaları', 'text', TRUE, 13),
    ('frm33', '4.1', 'Project Manager CV', 'Proje Müdürü Özgeçmişi', 'text', TRUE, 14),
    ('frm33', '4.2', 'HSE Manager CV', 'İSGÇ Müdürü Özgeçmişi', 'text', TRUE, 15),
    ('frm33', '4.3', 'HSE Team Organisation & Contacts', 'İSGÇ Takım Organizasyonu ve İletişim', 'text', TRUE, 16),
    ('frm33', '4.4', 'Project Organisation Chart', 'Proje Organizasyon Şeması', 'text', TRUE, 17),
    ('frm33', '4.5', 'Training Matrix', 'Eğitim Matrisi', 'text', TRUE, 18),
    ('frm33', '4.6', 'Annual Training Plan', 'Yıllık Eğitim Planı', 'text', TRUE, 19),
    ('frm33', '4.7', 'HSE Training Records', 'İSGÇ Eğitim Kayıtları', 'text', TRUE, 20),
    ('frm33', '5.1', 'Lifting & Hoisting Supervisors'' CV/Certificate', 'Kaldırma ve Yükseltme Süpervizörlerinin CV/Sertifikaları', 'text', TRUE, 21),
    ('frm33', '5.2', 'Riggers'' CV/Certificate', 'Rigging Uzmanlarının CV/Sertifikaları', 'text', TRUE, 22),
    ('frm33', '5.3', 'Crane Operators'' CV/Certificate', 'Vinç Operatörlerinin CV/Sertifikaları', 'text', TRUE, 23),
    ('frm33', '5.4', 'Professional Competency Certificates', 'Mesleki Yeterlilik Sertifikaları', 'text', TRUE, 24),
    ('frm33', '5.5', 'HSE Specialist Legal Contract', 'İSGÇ Uzmanı Yasal Sözleşmesi', 'text', TRUE, 25),
    ('frm33', '6.1', 'Annual HSE Activity Plan', 'Yıllık İSG Faaliyet Planı', 'text', TRUE, 26),
    ('frm33', '6.2', 'PPE Inspection & Delivery Forms', 'KKD Muayene & Teslim Formları', 'text', TRUE, 27);

-- Seed questions for FRM34
INSERT INTO frm_supervisor_questions (form_id, question_code, question_text_en, question_text_tr, question_type, is_required, position) VALUES
    ('frm34', '1.1', 'Approved Contract HSE Plan — Applicable to High Risk Contracts - Contract HSE Plans should describe how the Contractor works underneath, and interfaces with the SOCAR HSE Management System', 'Onaylanmış Sözleşme HSE Planı — Yüksek Riskli Sözleşmelere Uygulanabilir - Sözleşme HSE Planları, Yüklenicinin SOCAR HSE Yönetim Sistemi altında nasıl çalıştığını ve arayüz oluşturduğunu açıklamalıdır', 'text', TRUE, 1),
    ('frm34', '1.2', 'Subcontractor Audits', 'Alt Yüklenici Denetimleri', 'text', TRUE, 2),
    ('frm34', '1.3', 'Monthly HSE Report submitted', 'Aylık HSE Raporu sunuldu', 'text', TRUE, 3),
    ('frm34', '2.1', 'Vehicle & Equipment Inspections', 'Araç ve Ekipman Denetimleri', 'text', TRUE, 4),
    ('frm34', '2.2', 'Defensive Driver Training records', 'Defansif Sürücü Eğitim Kayıtları', 'text', TRUE, 5),
    ('frm34', '3.1', 'Approved Emergency Response Plan', 'Onaylanmış Acil Durum Müdahale Planı', 'text', TRUE, 6),
    ('frm34', '3.2', 'Designated First Aiders on site (10% of personnel)', 'Sahada Belirlenen İlkyardımcılar (%10 personel)', 'text', TRUE, 7),
    ('frm34', '3.3', 'Occupational Physician on site', 'Sahada İş Yeri Hekimi', 'text', TRUE, 8),
    ('frm34', '4.1', 'Project Manager mobilised', 'Proje Yöneticisi görevlendirildi', 'text', TRUE, 9),
    ('frm34', '4.2', 'HSE Manager mobilised', 'HSE Yöneticisi görevlendirildi', 'text', TRUE, 10),
    ('frm34', '4.3', 'HSE team resources (1 HSE person for 50 people)', 'HSE ekip kaynakları (50 kişi için 1 HSE personeli)', 'text', TRUE, 11),
    ('frm34', '4.4', 'HSE Training Records', 'HSE Eğitim Kayıtları', 'text', TRUE, 12),
    ('frm34', '5.1', 'Module 1 training - Induction', 'Modül 1 eğitimi - Oryantasyon', 'text', TRUE, 13),
    ('frm34', '5.2', 'Module 2 training - Work Authorisation', 'Modül 2 eğitimi - Çalışma İzni', 'text', TRUE, 14),
    ('frm34', '5.3', 'Worksite Hazard Management Procedures', 'Çalışma Sahası Tehlike Yönetim Prosedürleri', 'text', TRUE, 15),
    ('frm34', '5.4', 'Tool and Equipment inspections (color coding - lifting gear, electrical, power tools)', 'Alet ve Ekipman denetimleri (renk kodlama - kaldırma ekipmanı, elektrikli, el aletleri)', 'text', TRUE, 16);

-- Seed questions for FRM35
INSERT INTO frm_supervisor_questions (form_id, question_code, question_text_en, question_text_tr, question_type, is_required, position) VALUES
    ('frm35', '1.1', 'Do all drivers have valid drivers licence?', NULL, 'text', TRUE, 1),
    ('frm35', '1.2', 'Is there a specific Toolbox talk for the drivers?', NULL, 'text', TRUE, 2),
    ('frm35', '1.3', 'Are all vehicles inspected?', NULL, 'text', TRUE, 3),
    ('frm35', '1.4', 'Are there maintenance record of the vehicles on site?', NULL, 'text', TRUE, 4),
    ('frm35', '1.5', 'Have all drivers attended DDT?', NULL, 'text', TRUE, 5),
    ('frm35', '1.6', 'Are daily vehicle checks conducted by drivers?', NULL, 'text', TRUE, 6),
    ('frm35', '1.7', 'Are the driver and all passengers in the vehicle using their seat belts correctly? Is the driver complying with speed limits, maintaining safe following distances, and adhering to traffic signs and signals?', NULL, 'text', TRUE, 7),
    ('frm35', '1.8', 'Is a mobile phone being used while driving or in operational areas?', NULL, 'text', TRUE, 8),
    ('frm35', '1.9', 'Are daily vehicle inspections being carried out by the drivers?', NULL, 'text', TRUE, 9),
    ('frm35', '1.10', 'Are the vehicles parked in a manner that does not pose a traffic hazard within the facility and in alignment with the emergency exit direction?', NULL, 'text', TRUE, 10),
    ('frm35', '2.1', 'Are all lifting equipment inspected?', NULL, 'text', TRUE, 11),
    ('frm35', '2.2', 'Is color code implemented for all lifting gear?', NULL, 'text', TRUE, 12),
    ('frm35', '2.3', 'Are HARMS or Lifting Plans available on site?', NULL, 'text', TRUE, 13),
    ('frm35', '2.4', 'Are lifting appliances stored properly on site?', NULL, 'text', TRUE, 14),
    ('frm35', '2.5', 'Is there an updated register of all lifting gear on site?', NULL, 'text', TRUE, 15),
    ('frm35', '2.6', 'Do all riggers and operators have a valid certificate?', NULL, 'text', TRUE, 16),
    ('frm35', '2.7', 'Does all lifting gear and lifting equipment have 3rd party certificate?', NULL, 'text', TRUE, 17),
    ('frm35', '2.8', 'Have the lifting components been regularly subjected to load tests, and are the test results properly documented?', NULL, 'text', TRUE, 18),
    ('frm35', '3.1', 'Have proper Muster/Staging locations been provided and clearly posted?', NULL, 'text', TRUE, 19),
    ('frm35', '3.2', 'Can workers identify the emergency contact number?', NULL, 'text', TRUE, 20),
    ('frm35', '3.3', 'Are adequate fire extinguishers are in place and is proper training provided?', NULL, 'text', TRUE, 21),
    ('frm35', '3.4', 'Do workers understand the evacuation plan in case of an emergency?', NULL, 'text', TRUE, 22),
    ('frm35', '3.5', 'Are there sufficient number of designated first aiders on site (1:10)?', NULL, 'text', TRUE, 23),
    ('frm35', '3.6', 'Are sufficient first aid kits provided on site?', NULL, 'text', TRUE, 24),
    ('frm35', '3.7', 'Are there regular inspections of the kits?', NULL, 'text', TRUE, 25),
    ('frm35', '4.1', 'Is training matrix in place, updated and identified gaps closed?', NULL, 'text', TRUE, 26),
    ('frm35', '4.2', 'Do staff have HSE Passports?', NULL, 'text', TRUE, 27),
    ('frm35', '4.3', 'Do all staff have conducted HSE induction for the site (in relevant language)?', NULL, 'text', TRUE, 28),
    ('frm35', '4.4', 'Is specific training in place for supervisory staff (PTW, HARM)?', NULL, 'text', TRUE, 29),
    ('frm35', '4.5', 'Is competency program in place for HSE Critical positions?', NULL, 'text', TRUE, 30),
    ('frm35', '4.6', 'Is first line supervision available at the worksite?', NULL, 'text', TRUE, 31),
    ('frm35', '4.7', 'Is HSE Staff in place (1:50 or 1 per worksite)?', NULL, 'text', TRUE, 32),
    ('frm35', '5.1', 'Are H2S detectors and alarms situated in the workplace?', NULL, 'text', TRUE, 33),
    ('frm35', '5.2', 'Are alarms audible throughout site or alternative alarm available and known?', NULL, 'text', TRUE, 34),
    ('frm35', '5.3', 'Are all site personnel trained in H2S awareness and escape?', NULL, 'text', TRUE, 35),
    ('frm35', '5.4', 'Are personal escape equipment available for all personnel?', NULL, 'text', TRUE, 36),
    ('frm35', '5.5', 'Are escape routes and muster points identified and known to all?', NULL, 'text', TRUE, 37),
    ('frm35', '5.6', 'Are rescue plans and equipment in place?', NULL, 'text', TRUE, 38),
    ('frm35', '5.7', 'Has H₂S awareness training been updated at regular intervals and made mandatory for new employees? Is it consistently included in the training plans?', NULL, 'text', TRUE, 39),
    ('frm35', '5.8', 'In the event of H₂S dispersion, have emergency evacuation routes been clearly defined? Are H₂S detection devices available along these routes, and are the devices made suitable for personnel in accordance with SOCAR specifications?', NULL, 'text', TRUE, 40),
    ('frm35', '6.1', 'Is fitness to work process in place and maintained up to date?', NULL, 'text', TRUE, 41),
    ('frm35', '6.2', 'Is Heat Illness Prevention process in place, equipped and followed?', NULL, 'text', TRUE, 42),
    ('frm35', '6.3', 'Are welfare facilities provided at site?', NULL, 'text', TRUE, 43),
    ('frm35', '7.1', 'Is Waste Management Plan adhered to and resourced?', NULL, 'text', TRUE, 44),
    ('frm35', '7.2', 'Are site personnel trained in waste management?', NULL, 'text', TRUE, 45),
    ('frm35', '7.3', 'Is spill response equipment in place and maintained?', NULL, 'text', TRUE, 46),
    ('frm35', '7.4', 'Are site personnel trained in spill response?', NULL, 'text', TRUE, 47),
    ('frm35', '8.1', 'Are camp walkways and public areas are adequately lit?', NULL, 'text', TRUE, 48),
    ('frm35', '8.2', 'Are escape routes, muster points and refuge areas all identified and adequate?', NULL, 'text', TRUE, 49),
    ('frm35', '8.3', 'Are escape routes are maintained clear and trip free?', NULL, 'text', TRUE, 50),
    ('frm35', '8.4', 'Is electrical maintenance and testing conducted on a regular basis?', NULL, 'text', TRUE, 51),
    ('frm35', '8.5', 'Are sanitary facilities maintained in a clean and hygenic manner?', NULL, 'text', TRUE, 52),
    ('frm35', '8.6', 'Are recreation and welfare facilities provided?', NULL, 'text', TRUE, 53),
    ('frm35', '8.7', 'Are rest and social facilities provided?', NULL, 'text', TRUE, 54),
    ('frm35', '9.1', 'Scaffolding Checklist', NULL, 'text', TRUE, 55),
    ('frm35', '9.2', 'Is there sufficient barrier protection in areas with tensioned lines (chains, cables, ropes), belts, and spring devices? Is there adequate safety clearance between the workers'' hands/bodies and equipment such as cables and lock links when working with these devices?', NULL, 'text', TRUE, 56),
    ('frm35', '9.3', 'Have areas with moving equipment and rollable objects been secured? Are loads safely secured during lifting, loading, unloading, and transportation activities?', NULL, 'text', TRUE, 57),
    ('frm35', '9.4', 'Has it been confirmed that there is no energy present before intervening with or opening pressurized equipment? Is there any improper work in hazardous areas? Are pressurized gas cylinders secured, with caps in place and stored upright?', NULL, 'text', TRUE, 58),
    ('frm35', '9.5', 'Are there workers near equipment with parts that could move suddenly? Are safety devices functioning properly, and is there a risk of hand or finger entrapment?', NULL, 'text', TRUE, 59),
    ('frm35', '9.6', 'Is work being carried out on or near electrically energized equipment? Is a safe distance maintained to prevent arc flash, and are workers staying away from electrical tools when circuit breakers or fuses are being turned off?', NULL, 'text', TRUE, 60),
    ('frm35', '9.7', 'Has barrier protection been implemented to control or prevent flying debris and projectiles in tasks such as grinding, chiseling, abrasive blasting, and water spraying?', NULL, 'text', TRUE, 61),
    ('frm35', '9.8', 'During key-driven pushing or pulling operations, are workers keeping their faces and hands away from the hazardous area to avoid the sudden loosening of fasteners or slipping of the key?', NULL, 'text', TRUE, 62),
    ('frm35', '10.1', 'Is the site mandatory PPE worn?', NULL, 'text', TRUE, 63),
    ('frm35', '10.2', 'Is a HARM conducted for tasks to identify any other PPE requirements? If conditions change is PPE Selection reviewed?', NULL, 'text', TRUE, 64),
    ('frm35', '10.3', 'Is there a hand protection regime in place to identify that suitable gloves are worn for hazards encountered?', NULL, 'text', TRUE, 65),
    ('frm35', '10.4', 'Is there an eye protection programme in place specific to the scope of work?', NULL, 'text', TRUE, 66),
    ('frm35', '10.5', 'Is Fire Retardant Clothing worn at site?', NULL, 'text', TRUE, 67),
    ('frm35', '10.6', 'Is training provided regarding wearing/fitting/care of PPE?', NULL, 'text', TRUE, 68),
    ('frm35', '10.7', 'Are PPE free areas identified and clearly identified with relevant signage?', NULL, 'text', TRUE, 69),
    ('frm35', '10.8', 'Are individuals aware of routine for changing PPE if damaged?', NULL, 'text', TRUE, 70),
    ('frm35', '10.9', 'Are clear safety glasses available for internal work areas?', NULL, 'text', TRUE, 71),
    ('frm35', '10.10', 'Is relevant RPE available as required and fitted correctly for the individual?', NULL, 'text', TRUE, 72),
    ('frm35', '10.11', 'Have cleaning and disinfection procedures been established for personal protective equipment contaminated with chemical or biological substances?', NULL, 'text', TRUE, 73),
    ('frm35', '10.12', 'Has a protocol been established for the maintenance, repair, and replacement of personal protective equipment, and is this protocol regularly reviewed?', NULL, 'text', TRUE, 74),
    ('frm35', '10.13', 'Are escape masks worn and free of damage?', NULL, 'text', TRUE, 75),
    ('frm35', '11.1', 'Has a competent person inspected fall protection equipment and ladders before use?', NULL, 'text', TRUE, 76),
    ('frm35', '11.2', 'Has everyone working at height been trained in the use of fall protection equipment?', NULL, 'text', TRUE, 77),
    ('frm35', '11.3', 'Has a fall protection plan and specific rescue plans for those working at height been established; are regular drills conducted to ensure the effectiveness of these plans, and are emergency response procedures and rescue systems regularly inspected?', NULL, 'text', TRUE, 78),
    ('frm35', '11.4', 'Are suitable fall arrest systems in use for the height of work being conducted?', NULL, 'text', TRUE, 79),
    ('frm35', '11.5', 'Are harnesses and any fall arrest system certified, in date for inspection and inspected before use?', NULL, 'text', TRUE, 80),
    ('frm35', '11.6', 'Is 100% tie off protocol in place when individuals are working outside a protected area or exposed to a fall of greater than 1.8m or working next to gaps/openings?', NULL, 'text', TRUE, 81),
    ('frm35', '11.7', 'Tie off/Anchor points are above the work activity? (Only exception during scaffold erection)', NULL, 'text', TRUE, 82),
    ('frm35', '11.8', 'Are lanyards/Self retracting lines attached to anchor points that can hold 2,268kg, and is an approved tie off point?', NULL, 'text', TRUE, 83),
    ('frm35', '11.9', 'Do Scaffolds, Mobile work platforms and equipment for lifting people meet internationally recognised standards?', NULL, 'text', TRUE, 84),
    ('frm35', '12.1', 'Do scaffolds and access ways conform to international standards?', NULL, 'text', TRUE, 85),
    ('frm35', '12.2', 'Are scaffolds erected, altered and dismantled by competent certified persons?', NULL, 'text', TRUE, 86),
    ('frm35', '12.3', 'Is there a tag system in place?', NULL, 'text', TRUE, 87),
    ('frm35', '12.4', 'If a scaffold is considered incomplete, unsafe or being modified is the tag for the specific section removed and given to responsible person?', NULL, 'text', TRUE, 88),
    ('frm35', '12.5', 'Are all gaps closed on work platform to prevent items falling?', NULL, 'text', TRUE, 89),
    ('frm35', '12.6', 'In scaffolding areas with a risk of falling objects, is the lower section enclosed with a safety tape, or are safety nets used on the side railings? Additionally, are safety measures such as safety nets, safety tapes, and barriers implemented to prevent the risk of falling objects on work platforms? Are workers using appropriate equipment, such as buckets or boxes, to store their materials?', NULL, 'text', TRUE, 90),
    ('frm35', '12.7', 'Do scaffolding personnel have Safe Erection and Dismantling training?', NULL, 'text', TRUE, 91),
    ('frm35', '12.8', 'Are emergency rescue procedures in place and communicated to all scaffold users in case of an incident?', NULL, 'text', TRUE, 92),
    ('frm35', '12.9', 'Do scaffolding stair covers are closed during the work? And are the signs clearly posted?', NULL, 'text', TRUE, 93),
    ('frm35', '12.10', 'Is maintenance reporting for scaffold components being done, and are equipment inspections regularly conducted?', NULL, 'text', TRUE, 94),
    ('frm35', '12.11', 'Is there clear communication and adequate signage indicating scaffold status, load limits, and access restrictions?', NULL, 'text', TRUE, 95),
    ('frm35', '12.12', 'Are scaffold work areas free of obstructions and accessible for workers to move safely?', NULL, 'text', TRUE, 96),
    ('frm35', '13.1', 'Is a subject matter expert appointed and their roles/responsibilities clearly understood?', NULL, 'text', TRUE, 97),
    ('frm35', '13.2', 'Are all lifts correctly categorised and is relevant lifting plan in place?', NULL, 'text', TRUE, 98),
    ('frm35', '13.3', 'Are all individuals involved in the lifting process deemed competent? (Riggers, supervisor, operator and signalmen)', NULL, 'text', TRUE, 99),
    ('frm35', '13.4', 'Have ground conditions in area of lift been assessed before work commences?', NULL, 'text', TRUE, 100),
    ('frm35', '13.5', 'Is all lifting equipment in date inspection correctly colour coded/tagged?', NULL, 'text', TRUE, 101),
    ('frm35', '13.6', 'Are all cranes equipped with operating safeguarding and control systems? Is all relevant test documentation available with the crane?', NULL, 'text', TRUE, 102),
    ('frm35', '13.7', 'Are tag lines used and hands free/away from line of fire practices employed?', NULL, 'text', TRUE, 103),
    ('frm35', '13.8', 'Is the swing radius of the crane clearly defined and marked with warning tape?', NULL, 'text', TRUE, 104),
    ('frm35', '13.9', 'During lifting operations, is an effective communication protocol established between the operator and workers? Are signals, radios, and audible warnings being used?', NULL, 'text', TRUE, 105),
    ('frm35', '13.10', 'Are outriggers fully deployed, adequate size landing pads used and relevant barriers in place?', NULL, 'text', TRUE, 106),
    ('frm35', '13.11', 'Is a sole person in control of the lift with adequate communication/signals with the operator?', NULL, 'text', TRUE, 107),
    ('frm35', '13.12', 'Are audible/visible warnings used when flying loads over work areas?', NULL, 'text', TRUE, 108),
    ('frm35', '13.13', 'Are safe limits of approach followed when working near high voltage lines?', NULL, 'text', TRUE, 109),
    ('frm35', '14.1', 'Do Supervisors ensure work area is free from trip hazards, prior to, during and completion of works?', NULL, 'text', TRUE, 110),
    ('frm35', '14.2', 'Is the cable management sufficient on site? (Cable trees used, cables rolled up on completion of use)', NULL, 'text', TRUE, 111),
    ('frm35', '14.3', 'Is waste and debris removed from the work site in a timely manner?', NULL, 'text', TRUE, 112),
    ('frm35', '14.4', 'Is the waste being segregated?', NULL, 'text', TRUE, 113),
    ('frm35', '14.5', 'Are stairways, passageways, ladder access, scaffold platforms and gangways free from materials supplies and obstructions?', NULL, 'text', TRUE, 114),
    ('frm35', '14.6', 'Are there any controls and available equipment for leakages and spills?', NULL, 'text', TRUE, 115),
    ('frm35', '14.7', 'Are areas allocated for temporary storage/stockpiling/segregation of materials?', NULL, 'text', TRUE, 116),
    ('frm35', '14.8', 'Are emergency access and equipment easily available and not blocked?', NULL, 'text', TRUE, 117),
    ('frm35', '14.9', 'If there are operations involving chemicals in the work area, are appropriate materials and methods provided to control potential spills?', NULL, 'text', TRUE, 118),
    ('frm35', '14.10', 'Are slip, trip and fall hazards being managed properly and control mitigations are in place?', NULL, 'text', TRUE, 119);